apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    generation: 1
    labels:
      io.kompose.service: dexray3
    name: dexray3
    namespace: default
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/dexray3
  spec:
    replicas: 1
    selector:
      matchLabels:
        io.kompose.service: dexray3
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: dexray3
      spec:
        volumes:
        containers:
        - image: us.gcr.io/multichain-prod/dexray3:v1
          imagePullPolicy: Always
          name: dexray3
          ports:
          - containerPort: 3000
            protocol: TCP
          volumeMounts:
          resources: {}
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""