apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    name: dexray3
    namespace: default
    selfLink: /api/v1/namespaces/default/services/dexray3
  spec:
    ports:
    - name: "webserver"
      port: 80
      protocol: TCP
      targetPort: 3000
    selector:
      io.kompose.service: dexray3
    sessionAffinity: None
    type: LoadBalancer
  status:
    loadBalancer:
      ingress:
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""